# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias rmf="rm -f "
alias rmd="rm -rf "

alias lsal="ls -al"
alias lsa="ls -a"

alias clr="clear"

alias bashrc="vim ~/.bashrc && source ~/.bashrc"

alias dnfup="sudo dnf upgrade"
